### ISSUE TITLE
store-utils.lisp defines print-object method specializing on standard-object

### ISSUE THREAD

**Issue by dkochmanski** [html/weblocks-stores#3]
This is prohibited by CLHS 11.1.2.1.2 #19 causing ECL enter infinite recursion on any object

I'll try to fix it in ECL, altough problem remains

    (defmethod print-object ((obj standard-object) stream)
      (unless *debug-stores* 
        (return-from print-object (call-next-method)))
    
      (let ((id (ignore-errors (object-id obj))))
        (if id 
          (print-unreadable-object (obj stream :type t :identity t)
            (format stream "id=~4@A" id))
          (call-next-method))))

**Comment by html** [comment]
Method is still useful and works fine in SBCL.
It should not be loaded in ECL currently.
I've added comment related to method prohibition into project source.
